### ISSUE TITLE
Possible to integrate into my project?

### ISSUE THREAD

**Issue by akamensky** [augustl/path-travel-agent#3]
Hi @augustl 

Intro:
I have noticed your project while was trying to make some changes to Spark. As my changes did not made their way to the code (due to changing logic which owner of Spark does not want as it seems) I started working on [my own framework](https://github.com/akamensky/XpressJ) which inherits some concepts from Sinatra, but mainly follows Express.js logic as I find it way more flexible and convenient.

Relating to this project the difference with Spark is that order of routes matters since all matched routes will be executed. As I am just working on 0.x versions I initially used simple RegEx matching, but now as I get closer to release of 1.0.0 I would like to implement faster route matching.

It would be great if you can take a look at my project and maybe provide a pull request or at least give any suggestions.

Best,
Alex

**Comment by augustl** [comment]
Hey!

path-travel-agent needs some projects to ensure that it actually works and has a sane API. I'll submit a PR for integration with your project. I'm on parental leave at the moment and I might go AFK for a couple of days now, but I'll let you know as soon as I have something.

**Comment by akamensky** [comment]
That would be great. I will be waiting for your pull request.

**Comment by augustl** [comment]
I get the following error when I try to run the tests for XpressJ. There are some exceptions, and the test run seems to hang until I interrupt with ctrl^C. Any idea what might be wrong?

```
augustl@quark ~/c/XpressJ> mvn test
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 5 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 5 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] parent
[INFO] xpressj-api
[INFO] xpressj-jetty
[INFO] xpressj
[INFO] xpressj-simple-server
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building parent 0.7.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ parent ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xpressj-api 0.7.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ xpressj-api ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ xpressj-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/augustl/code/XpressJ/xpressj-api/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ xpressj-api ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ xpressj-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/augustl/code/XpressJ/xpressj-api/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ xpressj-api ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ xpressj-api ---
[INFO] No tests to run.
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xpressj-jetty 0.7.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ xpressj-jetty ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ xpressj-jetty ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ xpressj-jetty ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ xpressj-jetty ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/augustl/code/XpressJ/xpressj-jetty/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ xpressj-jetty ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ xpressj-jetty ---
[INFO] No tests to run.
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xpressj 0.7.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ xpressj ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ xpressj ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/augustl/code/XpressJ/xpressj/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ xpressj ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /Users/augustl/code/XpressJ/xpressj/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ xpressj ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ xpressj ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ xpressj ---
[INFO] Surefire report directory: /Users/augustl/code/XpressJ/xpressj/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running xpressj.ErrorPagesTest
2014-08-08 13:31:40.750:INFO::Thread-1: Logging initialized @390ms
** Configured to listen on 0.0.0.0:8081
** XpressJ has started ...
** Configured to listen on 0.0.0.0:8082
** XpressJ has started ...
java.lang.NullPointerException: test error
    at xpressj.ErrorPagesTest$5.handle(ErrorPagesTest.java:84)
    at xpressj.route.RouteImplImpl.handle(RouteImplImpl.java:118)
    at xpressj.server.RequestHandler.handle(RequestHandler.java:71)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)
    at org.eclipse.jetty.server.Server.handle(Server.java:461)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException: test error
    at xpressj.ErrorPagesTest$6.handle(ErrorPagesTest.java:90)
    at xpressj.route.RouteImplImpl.handle(RouteImplImpl.java:118)
    at xpressj.server.RequestHandler.handle(RequestHandler.java:71)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)
    at org.eclipse.jetty.server.Server.handle(Server.java:461)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
    at java.lang.Thread.run(Thread.java:745)
** XpressJ is stopping ...
** XpressJ has stopped ...
** XpressJ is stopping ...
** XpressJ has stopped ...
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.477 sec
Running xpressj.GeneralIntegrationTest
** Configured to listen on 0.0.0.0:8081
** XpressJ has started ...
** XpressJ is stopping ...
** XpressJ has stopped ...
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.163 sec
Running xpressj.MultiplePortsTest
** Configured to listen on 0.0.0.0:8081
** Configured to listen on 0.0.0.0:8082
** XpressJ has started ...
** XpressJ is stopping ...
** XpressJ has stopped ...
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec
Running xpressj.PerformanceBenchmarkTest
** Configured to listen on 0.0.0.0:8081
** XpressJ has started ...
^C
Results :

Tests run: 16, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by akamensky** [comment]
That is by design. It is a part of test that server should send 500 page in case if any error (exception) happens. As you can see it shows that all tests passed.

**Comment by augustl** [comment]
Ah, I was fooled by the fact that the test run hangs until I ctrl+c.

I have a question about one of your APIs. A `RouteMatcher` implements `public List<RouteImpl> getMatchingRoutes(String httpMethod, String uri)`, and a `RouteImpl` implements `public boolean match(String httpMethod, String path)`. That seems like a duplicate to me. Does it make sense to change this, so that for example the RouteMatcher returns a single Route instance, removing the `RouteImpl` interface alltogether?

**Comment by akamensky** [comment]
Not really. This is actually the requirement to return the list of all matching routes. All routes that were positively matched for requested URI will be executed. And specially important is the order of addition of those routes as they must be executed exactly in that order.

**Comment by augustl** [comment]
Hmm, github doesn't seem to have received my e-mail response, so I'll write it here again.

Why are the signatures the same? We've already found all matching routes for httpMethod + url, why does the RouteImpl also have a method with the same httpMethod + url signature?

**Comment by akamensky** [comment]
If you look at the actual implementation of those classes in xpressj/src/main/java/xpressj/route then you can see that what happens is on incoming request webserver would call RouteMatcher#getMatchingRoutes and pass HTTP method and URI as parameters. Then inside RouteMatcher it will iterate through list of RouteImpl (as those are stored in ArrayList inside RouteMatcher instance) and call match method passing those parameters; this method in its turn will return true/false depends on matching results.

As side note, those interfaces are not necessary for API as implementation is done only once, however since those methods will be called from web server I put them in API. Please look at xpressj-jetty/src/main/java/xpressj/server/RequestHandler#handle method. I do have in plan to rework this part to exclude those interface from API. So if you have any suggestion how to better organize logic/classes - I would love to hear or maybe even get PR.

Best,
Alex

**Comment by augustl** [comment]
Thanks for the detailed explanation! I see now that RouteMatcherImpl's getMatchingRoutes is the "top level call" that takes method + url, and that it calls .match with a similar method signature on all its routes. Because of the way PTA works, it might not make sense to implement the RouteImpl interface's match method. In that vein, it makes sense to have two different interfaces for matching and responding. When getMatchingRoutes returns a list of routes, the only method that is called on the RouteImpl is "handle". So "leaking" match to the outside doesn't make much sense imo.

**Comment by augustl** [comment]
Closing this issue, we can discuss further in the referenced pull request :)
